apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nextcloud-nginx-secrets
  annotations:
  labels:
    {{- include "nextcloud-nginx.selectorLabels" . | nindent 4 }}
data:
  DBNAME: {{ .Values.secrets.DBNAME }}
  DBPASS: {{ .Values.secrets.DBPASS }}
  DBUSER: {{ .Values.secrets.DBUSER }}
  PASSWORDSALT: {{ .Values.secrets.PASSWORDSALT }}
  S3KEY: {{ .Values.secrets.S3KEY }}
  S3SECRET: {{ .Values.secrets.S3SECRET }}
  SECRET: {{ .Values.secrets.SECRET }}
